### PR TITLE
feat: add docusaurus, clear boilerplate

### PR DESCRIPTION
**Pull request by zpg6**
Kicking things off by clearing the boilerplate and switching the color palette a bit.

swiftui-react-native

Thoughts on this is a starter logo? lol

### CODE REVIEW

**Comment by zpg6** [comment]
Screen Shot 2022-02-26 at 9 37 03 AM
image

**Comment by andrew-levy** [comment]
This is awesome, thanks for setting this up!  Love the logo - can we make it so that the circle with the swiftui logo is smaller like the usual "nucleus" of the react logo?

**Comment by zpg6** [comment]
> can we make it so that the circle with the swiftui logo is smaller like the usual "nucleus" of the react logo?

Definitely!

**Comment by zpg6** [comment]
Group@1 5x

It may be pretty hard to see the bird though

**Comment by andrew-levy** [comment]
I like it! Doesn't have to be perfect and we can mess around with different designs.

**Comment by zpg6** [comment]
Looks like I don't have permissions to add vercel-bot with previews for it. 

If you sign into Vercel w/ GitHub for a hobby account (no cc), you can import this repo and deploy the `/docs` folder as a docusaurus app in a few clicks.

For now:
```
cd docs
npm run start
```

**Comment by zpg6** [comment]
srn-header

Playing around with what might be a cool README header

**Comment by zpg6** [comment]
@andrew-levy what would you consider Definition of Done for this PR?

My thought was:
- [ ]  Add an empty page for each of the exports
- [ ]  Copy/Add a description in for each
- [ ]  Add a code example for each

Further Work
- Add more examples for each?
- Add screenshots of those examples for iOS/Android?
    - Can we show live demo like react native docs?

**Comment by andrew-levy** [comment]
Yes and maybe a code example? Or would that be too much.

**Comment by zpg6** [comment]
> Yes and maybe a code example? Or would that be too much.

If you wanted to tag in, I won't have bandwidth until tomorrow to finish what's left in the (updated) list above.

**Comment by andrew-levy** [comment]
Of course, happy to help. I can probably work on it tomorrow and throughout the week.

**Comment by zpg6** [comment]
I'm committed up, I'll leave a note here if I pop back in. Do the same if you don't mind since we'll likely criss-cross on some files.

**Comment by zpg6** [comment]
> I'm committed up, I'll leave a note here if I pop back in. Do the same if you don't mind since we'll likely criss-cross on some files.

Hopped in to create empty pages, back out now. Will be back in a few hours to add some more content. There's a lot of pages, lol, don't be afraid to leave me some.

**Comment by andrew-levy** [comment]
cool thanks i'll be on later today to take a look and work on some 

getting a build error when building to vercel

**Comment by andrew-levy** [comment]
also, what were you using to make the logo? photoshop?

**Comment by zpg6** [comment]
> getting a build error when building to vercel

I had two broken links, fixed now and my build passes locally. Is Vercel is pointed to the 'docs' folder?

**Comment by zpg6** [comment]
New logo looks nice

**Comment by zpg6** [comment]
Your ForEach SwiftUI snippet, check your variable names :)

**Comment by andrew-levy** [comment]
> Your ForEach SwiftUI snippet, check your variable names :)

Good catch! thanks. gona be making more edits tomorrow

**Comment by zpg6** [comment]
> > Your ForEach SwiftUI snippet, check your variable names :)
> 
> Good catch! thanks. gona be making more edits tomorrow 

Should we split this into a few issues so we can work async?

**Comment by andrew-levy** [comment]
I can work from the bottom up. You can go from the top down and we can meet in the middle. So ill take:
- utilities
- hooks
- providers
- controls
How does that sound?

**Comment by andrew-levy** [comment]
Almost done with the ones I committed to. got stuck on a few things regarding `SwiftUIRoot`, `useEnvironment` and `Group`, but they are both tested and merged into master and this branch. I have documented how `SwiftUIRoot` and `useEnvironment` work together similar to how the .environment() and @Environment works in siwftui. Let me know if you need me to explain any of those changes.

**Comment by andrew-levy** [comment]
Update: Did my first round of testing and found a chunk of small bugs that have all been fixed! I am trying out all scenarios of each component, both alone and composed with other views.

**Pull request merged**
