### PR TITLE
added new color system to components

### LINKED ISSUE #12: Possible new color system
## Currently there are a few ways to apply colors to views:

1. `UIColor` object. This is an object you can import that has `dark` and `light` properties. Inside those, there are each individual colors. 

2. `useUIColor` hook. this hook returns a dynamic form of the above UIColor object that decides between dark and light based on the current color scheme. 

3. You can also just pass in a hex value or any of the built in react native color values. 

## Proposed System:

Pass in the name of the swiftui color (as a string) that will map to the correct hex value. This will provide autocomplete and users won't need to use the hook or object.

example:
`backgroundColor=“systemBlue”`

where,
`type backgroundColor = keyof UIColor.light | string` or something like that. 

The logic would go something like this:
- if the string is a key of one of the uicolors, use the corresponding value
- else, just use that value as its probably a hex or rgba value.

In order to incorporate dark mode, we would have to use the `useColorScheme` hook internally within each component rather than having the user use it (I like this better - less work for the user). 

utils/colors
```typescript 
const getColor = (color: string, colorScheme: 'dark' | 'light') => {
  const palette = UIColor[colorScheme];
  if (palette[color]) return palette[color]
  return color
};
```

then in each component 
```jsx 
const colorScheme = useColorSheme();

…getColor(backgroundColor, colorScheme),
```

Open questions:
- Should we still include the old way to get colors?
- Does the autocompleting just work for TS or does it work for JS too? 
- Should we also do this with alignment, fonts, etc? yes i think

### PR DESCRIPTION
**Pull request by andrew-levy**
To Do:
- [x] Update how colors are input
- [x] Update Fonts
- [x] Update Alignments
- [x] Remove an unnecessary objects from index.ts

### CODE REVIEW

**Comment by andrew-levy** [comment]
I removed the utility objects `UIColor`, `Font`, `FontWeight`, and `Alignment` from the package for external use. We still use them internally, but the user no longer needs to import them. Instead, users simply use strings (with the help of autocomplete and TS) to specify fonts, weights, colors, and alignments.

I kept the `useUIColor()` hook because users might want to access the dynamic color palette outside of the views we provide.

@zpg6 Mind trying this out when you get a chance?

**Comment by zpg6** [comment]
> I removed the utility objects `UIColor`, `Font`, `FontWeight`, and `Alignment` from the package for external use. We still use them internally, but the user no longer needs to import them. Instead, users simply use strings (with the help of autocomplete and TS) to specify fonts, weights, colors, and alignments.

Only thing I will say is that based on some logic, implementer may want to conditionally align, change font weight, etc. Does this prevent that in any way?

> I kept the `useUIColor()` hook because users might want to access the dynamic color palette outside of the views we provide.

Nice, I like this for reasoning in my first comment.

> @zpg6 Mind trying this out when you get a chance?

👍

**Comment by andrew-levy** [comment]
> Only thing I will say is that based on some logic, implementer may want to conditionally align, change font weight, etc. Does this prevent that in any way?

Nope the user has full control over fonts, weights, colors and alignments, the only thing that changes is how

**Comment by andrew-levy** [comment]
Heres an example @zpg6 

Old way:

```tsx
<VStack alignment={Alignment.center} backgroundColor={UIColor.systemGray6}>
   <Text font={Font.body} fontWeight={FontWeight.bold}>some text</Text>
</VStack>
```

New way:

```tsx
<VStack alignment="center" backgroundColor="systemGray6">
   <Text font="body" fontWeight="bold">some text</Text>
</VStack>
```

**Comment by zpg6** [comment]
They call code like that syntactic sugar I think? Lol, looks awesome!!

**Pull request merged**
