### PR TITLE
Fix: View replaced with ScrollView

### LINKED ISSUE #32: List component is not scrollable
### `List` api lacks of scroll

swiftui

### PR DESCRIPTION
**Pull request by anday013**
This change resolves #32 by replacing `View` with `ScrollView`

### CODE REVIEW

**Comment by andrew-levy** [comment]
Hey @anday2000 thanks for making this change. I'm out of town this weekend but can test this out tomorrow when i get back.

Also please let me know if you find any other issues while using the library! PRs are much appreciated

**Comment by anday013** [comment]
Hey @andrew-levy  thank you for such a cool project, I loved it! 

Sure, I'll continue to play around with it, and contribute if something is missing or not working as expected.

**Comment by andrew-levy** [comment]
@anday2000 In SwiftUI, using a List makes the whole screen scrollable, not just the content of that list. I'm not sure if this change is going to provide the best experience that matches SwiftUI as closely as possible. I tried this change in my current app, and it was causing strange nested scrolling issues, especially with the `insetGrouped` list style. Are you able to just use a ScrollView around your list to make it scrollable for now, at least until I can find a better solution for this?

**Comment by anday013** [comment]
@andrew-levy I am not sure that the scenario you described is the default behaviour of the `List` component in SwiftUI. Thus, I attached a demo of `List` with the content above its reach, that stays put:
swiftui

**Comment by andrew-levy** [comment]
Okay i see what you're saying now. I think this will be a little more complex than just switching the view to a scrollview. There are a few other considerations:
- I think the outter most view in the `List` component would need to be the scroll view
- What happens if we have multiple lists on the page? I was thinking about adding a `Section` component to handle this.
- What happens if the list is put inside of another scroll view? what should the behavior be. 
- `List` should fill the remaining space of the screen (currently doesnt work this way, so I dont think it would be possible right now to replicate the swiftui demo you provided ^)

I think this is worth implementing, but might take a bit more time to make sure we do it the right way. Are you cool with me taking some time to look into that? Please feel free to try to implement it yourself if you're interested, but i will also see if i can get the above criteria working. Let me know if you have any more thoughts. @anday2000

**Comment by andrew-levy** [comment]
@anday2000  Just an update on this. I made the list scrollable, and if you wan't to add more than one set of items, I added a new `Section` component. No need to add a scrollview manually anymore. I am going to do a bit more testing, and once I think it's in a good state, I can push out an update (likely will be a breaking change since List's props and behavior will change slightly. Do let me know if you have any thoughts on my approach here. 

https://user-images.githubusercontent.com/29075740/227629929-79f9c3f4-1eb9-40a2-8acc-ada1f6f27ca2.mov

**Comment by anday013** [comment]
@andrew-levy Sections look cool 👍 I'm curious about the scenario when there is no `Section` component inside the `List`, just plain iteration over cells like this: 
Screenshot 2023-03-26 at 19 00 51

Will it be also handled in a scrollable way?

**Comment by andrew-levy** [comment]
yes! forgot to add that to my example. it will be scrollable even without the section. I just needed to move a lot of the styling and logic out of the list component.

**Pull request closed without merging**
