### PR TITLE
feat: Added rotationEffect in SwiftUI style

### PR DESCRIPTION
**Pull request by zpg6**
A play on the existing scaleEffect, but rotation. I have done a fair amount of testing using degrees, but I don't use radians often enough to know a ton of edge cases.

### CODE REVIEW

**Comment by andrew-levy** [comment]
Hey thanks for adding this. One thing I noticed is that if both scale and rotate effects are provided, then whichever came last will override the first:
```jsx
          ...getRotationEffect(rotationEffect), // this will get overridden 
          ...getScaleEffect(scaleEffect), // by this
```

To fix this, I think we can abstract the "transform" logic to a `getTransform(scaleEffect, rotationEffect)` helper fn. What do you think?

**Comment by zpg6** [comment]
> To fix this, I think we can abstract the "transform" logic to a `getTransform(scaleEffect, rotationEffect)` helper fn. What do you think?

```
              ...getScaleEffect(scaleEffect),
        },
        getRotationEffect(rotationEffect),
```

I pulled it out for now to avoid conflicts. I think in proper SwiftUI form we could add the other variantions of `rotate()`. If we just add those outside where I have getRotationEffect, we wouldn't need the Fn I don't think.

**Comment by zpg6** [comment]
Also, I skipped adding to Picker, Link, and a few more. Mostly when rotation would be silly and behavior unexpected. Could test each individually against SwiftUI I suppose.

**Comment by andrew-levy** [comment]
Im not sure if this will work as expected. Since rotation and scale live within the same `transform` style object, they will need to be set together. Like
```javascript
const getTransform(scaleEffect, rotationEffect) => {
   // logic to format values based on inputs here...
   return { transform: [{ scale: scaleEffect }, { rotate: rotationEffect}] }
}
````

**Comment by zpg6** [comment]
I'm not sure if how I had it does either, but which allows the implementer to control the precedence of them? When we let them rotate in multiple directions order will matter.

**Comment by andrew-levy** [comment]
I think the only way to do this is to set them together with the same helper function. We need to only set the transform style property once, supplying it with rotation and scale.

**Comment by zpg6** [comment]
Okay, I think I see now. Should we move `main` to the `getTransform` with just the `scaleEffect` first?

**Comment by andrew-levy** [comment]
So the idea is to combine the scale and rotation helpers like so:
```typescript
export const getTransform = (scaleEffect: number, rotationEffect: Rotation) => {
  if (!scaleEffect && !rotationEffect) return null;

  let rotate;
  let scale = scaleEffect;
  if (rotationEffect?.degrees) {
    rotate = Math.round(rotationEffect.degrees) + "deg";
  } else if (rotationEffect?.radians) {
    rotate = rotationEffect.radians + "rad";
  }
  return {
    transform: [{ rotate }, { scale }],
  };
};
```

Then, we can replace 
```tsx
          ...getRotationEffect(rotationEffect),
          ...getScaleEffect(scaleEffect),
```
with 

```tsx
          ...getTransform(scaleEffect, rotationEffect),
```

Please let me know if you need me to explain further.

**Comment by zpg6** [comment]
Made that change without removing what we had before.

**Review by zpg6 — COMMENTED** [review]
Nice! Took good notes on where my formatting was off for next time.

**Comment by zpg6** [comment]
I've rotated tons of stuff, haha. Looks good by my testing. 

When you don't have the available frame to rotate and show anything, it doesn't grow the frame to accomodate. I'm assuming that's out of scope here?

**Pull request merged**
